### ISSUE TITLE
Create a 'deploy to heroku' button

### ISSUE THREAD

**Issue by philipbelesky** [jolynch/mit-tab#61]
Hi! Just a heads up that [tabbycat](https://github.com/czlee/tabbycat) has a pretty similar architecture to mit-tab, and we've found it pretty easy to add an [app manifest](https://github.com/czlee/tabbycat/blob/develop/app.json) that allows for a 'one click' method of [deploying to heroku](https://devcenter.heroku.com/articles/heroku-button). It might be worth looking into to help make mit-tab more accessible to setup.

**Comment by BenMusch** [comment]
@philipbelesky this would require significant change to mit-tab, since it uses sqlite for the database, which isnt supported by Heroku. The back-up system depends on sqlite, so there would need to be significant refactoring to support postgres instead. I've set up [this repo] to create a web app to handle the deployment, which should make it more accessible
